### ISSUE TITLE
Customize App\User model namespace

### ISSUE THREAD

**Issue by tinyoverflow** [Laralum/Users#6]
Hey,

by default you're using App\User, but in my case the User model is in the App\Models namespace.

It would be cool if you could add a way to change the used model via config (like in the auth.php config file).

**Comment by ConsoleTVs** [comment]
Yes ideed, this features is missing and must be somehow present!, we will do that, thanks!

**Comment by ConsoleTVs** [comment]
We extended the one Auth uses, so from the next release, the model will extend the same file as Auth do. To change it, check config.auth.providers.users.model :)
